# Generated by Django 3.0.5 on 2022-05-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='topping_name',
            field=models.TextField(),
        ),
    ]
