# Generated by Django 3.0.5 on 2022-05-07 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Media'),
            preserve_default=False,
        ),
    ]
