# Generated by Django 3.0.5 on 2022-05-07 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_pizza_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='image',
        ),
    ]
